### ISSUE TITLE
How to deal with testcontainers during tests?

### ISSUE THREAD

**Issue by svenruppert** [jitpack/jitci#10]
If you have to deal with web apps, writing a web-component for example, you need selenium to test. This is easy with testcontainers. How to deal with DockerInDocker?

**Comment by FrogDevelopper** [comment]
Hello,

I'd like to use JitCI, but hadn't be able to use Testcontainers during the tests.

> Caused by: java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration

How do I configure JItCi to use it ?
