### ISSUE TITLE
JitPack building 'gh-pages' branch

### ISSUE THREAD

**Issue by gmitch215** [jitpack/jitci#30]
Hello,
JitPack seems to attempt to build the `gh-pages` branch, even when no pom.xml / build.gradle is present. Is there a way to disable the building on this branch? I hope that in the future it will automatically ignore builds on this branch.

**Comment by gmitch215** [comment]
Bumping again...

**Comment by jitpack-io** [comment]
Hi

There's no dedicated setting for excluding branches at the moment but that would be good enhancement. 👀
